baseURL: ""
languageCode: en-us
title: My New Hugo Site
theme: PaperMod

params:
  homeInfoParams:
    Title: 'Helo everyone'
    Content: "That's it"
  

menu:
  main:
    - identifier: categories
      name: Categories
      url: /categories/
      weight: 10